analysing_hospital_operations_task:
  description: >
    With only the available data, deeply analyse it. This is a Singapore public hospital.
    Hospital knowledge should be extensively checked. 
    The lower the repeated visits to first visits ratio the better.
    Median wait time for outpatient should be less than 14 days.
    Common knowledge should be considered to explain certain trends but only when they are important. 
    Example of common knowledge is some months may experience lower demand due to holidays.
    Most commonly known seasonal trends don't have to be commented on.
  expected_output: >
    A list of notable findings that should be paid attention to.
  agent: senior_analyst
